name: Health Check

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: thebadams/level-up-builder

      - uses: pnpm/action-setup
        with:
          version: 8
      - uses: actions/setup-node
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run health
